name: robots_txt
version: 2.2.0+3

description: A complete, dependency-less and fully documented `robots.txt` ruleset parser.

homepage: https://github.com/vxern/robots_txt
repository: https://github.com/vxern/robots_txt
issue_tracker: https://github.com/vxern/robots_txt/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0 # Used for static analysis.

dev_dependencies:
  test: ^1.22.1 # Testing.
  words: ^0.2.0 # Stricter lints.
