name: robots_txt
version: 2.0.0

description: >-
  A lightweight `robots.txt` ruleset parser to ensure your application adheres
  the de facto standard.

homepage: https://github.com/wordcollector/robots_txt
repository: https://github.com/wordcollector/robots_txt
issue_tracker: https://github.com/wordcollector/robots_txt/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  web_scraper: ^0.1.4

dev_dependencies:
  words: ^0.2.0
